### ISSUE TITLE
The plugin makes Homebridge crash sometimes

### ISSUE THREAD

**Issue by kskaret** [rwifall/homebridge-sonybraviatv#2]
Resulting in the following stacktrace:

/usr/local/lib/node_modules/homebridge-sonybraviatv/index.js:53
      this.log("Error getting TV status (status code %s): %s", response.statusCode, err);
                                                                       ^

TypeError: Cannot read property 'statusCode' of undefined
    at SonyBraviaTVAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-sonybraviatv/index.js:53:72)
    at self.callback (/usr/local/lib/node_modules/homebridge-sonybraviatv/node_modules/request/request.js:373:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-sonybraviatv/node_modules/request/request.js:971:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:267:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
(END)

I run Homebridge on Raspberry Pi.

**Comment by rwifall** [comment]
I assume that you have some situations where your Raspberry Pi cannot connect to your TV?
This should be fixed by commit 04832cf71d0b9e665514b0256202d0072e716842

**Comment by kskaret** [comment]
Thanks!
